# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    templates:
      - docs-on-readthedocs
    vars:
      rtd_webhook_id: '47941'
    check:
      jobs:
        - airship-berth-docker-build-gate
    gate:
      jobs:
        - airship-berth-docker-build-gate
    post:
      jobs:
        - airship-berth-docker-publish

- nodeset:
    name: airship-berth-single-node
    nodes:
      - name: primary
        label: ubuntu-xenial

- job:
    name: airship-berth-docker-build-gate
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: airship-berth-single-node
    vars:
      publish: false
      tags:
        dynamic:
          patch_set: true

- job:
    name: airship-berth-docker-publish
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: airship-berth-single-node
    secrets:
      - airship_berth_quay_creds
    vars:
      publish: true
      tags:
        dynamic:
          branch: true
          commit: true
        static:
          - latest

- secret:
    name: airship_berth_quay_creds
    data:
      username: !encrypted/pkcs1-oaep
        - CHANGEME=
      password: !encrypted/pkcs1-oaep
        - CHANGEME=
